name: bitsdojo_window_platform_interface_v3
description: A common platform interface for the bitsdojo_window plugin.
homepage: https://github.com/DartGit-dev/bitsdojo_window/bitsdojo_window_platform_interface_v3
# NOTE: We strongly prefer non-breaking changes, even at the expense of a
# less-clean API. See https://flutter.dev/go/platform-interface-breaking-changes
version: 3.0.0

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.9.1
  plugin_platform_interface: ^2.1.4

dev_dependencies:
  pedantic: ^1.11.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
